let currentQuestionIndex=0;let correctCount=0;let incorrectCount=0;let currentInput="";let incorrectAttempts=0;let isKeyboardVisible=!0;function shuffleQuestions(){for(let i=questions.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[questions[i],questions[j]]=[questions[j],questions[i]]}}
function showNextQuestion(){const question=questions[currentQuestionIndex];document.getElementById("questionText").innerText=`「${question.japanese}」`;document.getElementById("questionIndex").innerText=`問題 ${currentQuestionIndex + 1} / ${questions.length}`;document.getElementById("correctCount").innerText=`正解: ${correctCount}`;document.getElementById("incorrectCount").innerText=`不正解: ${incorrectCount}`;currentInput="";document.getElementById("inputField").value=currentInput;document.getElementById("answerDisplay").style.display="none";incorrectAttempts=0;document.getElementById("backButton").style.display="none";document.getElementById("nextButton").style.display="none"}
function showLetter(letter){currentInput+=letter;document.getElementById("inputField").value=currentInput}
function deleteLastLetter(){currentInput=currentInput.slice(0,-1);document.getElementById("inputField").value=currentInput}
function clearAll(){currentInput="";document.getElementById("inputField").value=currentInput}
function showAnswer(){const correctAnswer=questions[currentQuestionIndex].english;if(currentInput.toLowerCase()===correctAnswer.toLowerCase()){correctCount++;document.getElementById("correctImage").style.display="block";document.getElementById("incorrectImage").style.display="none";setTimeout(()=>{document.getElementById("correctImage").style.display="none";currentQuestionIndex++;if(currentQuestionIndex<questions.length){showNextQuestion()}else{document.getElementById("keyboard").style.display="none";document.getElementById("retryButton").style.display="block";document.getElementById("backButton").style.display="block";document.getElementById("nextButton").style.display="block"}},1000)}else{incorrectAttempts++;incorrectCount++;document.getElementById("incorrectImage").style.display="block";document.getElementById("correctImage").style.display="none";setTimeout(()=>{document.getElementById("incorrectImage").style.display="none";if(incorrectAttempts>=3){showAnswerText()}else{document.getElementById("inputField").value="";currentInput=""}},1000)}}
function showAnswerText(){const correctAnswer=questions[currentQuestionIndex].english;document.getElementById("answerDisplay").innerText=`正解は: ${correctAnswer}`;document.getElementById("answerDisplay").style.display="block";document.getElementById("inputField").value="";currentInput=""}
function retryGame(){currentQuestionIndex=0;correctCount=0;incorrectCount=0;shuffleQuestions();showNextQuestion();document.getElementById("keyboard").style.display="grid";document.getElementById("backButton").style.display="none";document.getElementById("retryButton").style.display="none";document.getElementById("nextButton").style.display="none"}
function toggleKeyboard(){isKeyboardVisible=!isKeyboardVisible;document.getElementById("keyboard").style.display=isKeyboardVisible?"grid":"none";document.getElementById("keyboardToggleButton").innerText=isKeyboardVisible?"キーボード OFF":"キーボード ON";localStorage.setItem("keyboardVisible",isKeyboardVisible)}
window.onload=()=>{const savedState=localStorage.getItem("keyboardVisible");if(savedState!==null){isKeyboardVisible=savedState==="true"}
document.getElementById("keyboard").style.display=isKeyboardVisible?"grid":"none";document.getElementById("keyboardToggleButton").innerText=isKeyboardVisible?"キーボード OFF":"キーボード ON";shuffleQuestions();showNextQuestion()};window.addEventListener("keydown",(event)=>{if(!isKeyboardVisible){const key=event.key.toLowerCase();if(key==="backspace"){deleteLastLetter()}else if(key==="enter"){showAnswer()}else if(/^[a-z,-]$/.test(key)){showLetter(key)}}})